version: '3.8'

services:
  db:
    image: mariadb:10.4.22
    ports:
      - '3330:3306'
    volumes:
      - 'db_data:/var/lib/mysql:rw'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskapp
      MYSQL_USER: root
      MYSQL_PASSWORD: P@tchssw0rd
    restart: on-failure
    networks:
      - database
  nginx:
    image: nginx:1.19.0-alpine
    tty: true
    ports:
      - "8086:80"
    restart: on-failure

    volumes:
      - .:/var/lumiotestapp
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - server
    environment:
      - APP_ENV=dev
  php:
    build:
      context: .
    image: lumio-task/php:dev
    container_name: php
    volumes:
      - '.:/var/lumiotestapp'
      - './docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini'
    restart: on-failure
    working_dir: /var/lumiotestapp
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    depends_on:
      - db
    networks:
      - server
      - database

  composer:
    image: 'composer:latest'
    command: install
    volumes:
      - '.:/var/lumiotestapp'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
        - 8084:80
    depends_on:
      - db
    environment:
        PMA_ARBITRARY: "1"
        #PMA_HOST: "mariadb"
    volumes:
        - /sessions
    networks:
      - database

volumes:
  db_data: null

networks:
  database: null
  server:
    driver: bridge
